#!/bin/sh
########################################################################
# Begin $rc_base/init.d/mountfs
#
# Description : File System Mount Script
#
# Authors : Gerard Beekmans - gerard@linuxfromscratch.org
## Version : 00.00
#
# Notes :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
start)
	boot_mesg "Remounting root file system in read-write mode..."
	mount -n -o remount,rw / >/dev/null
	evaluate_retval

	# Remove fsck-related file system watermarks.
	rm -f /fastboot /forcefsck
	boot_mesg "Recording existing mounts in /etc/mtab..."
	> /etc/mtab
	mount -f / || failed=1
	mount -f /proc || failed=1
	mount -f /sys || failed=1
	(exit ${failed})
	evaluate_retval

	# This will mount all filesystems that do not have _netdev in
	# their option list. _netdev denotes a network filesystem.
	boot_mesg "Mounting remaining file systems..."
	mount -a -O no_netdev >/dev/null
	evaluate_retval

	# mount tmp fs.
	boot_mesg "re-mount /tmp..."
	mkdir /dev/shm/tmp
	chmod 1777 /dev/shm/tmp
	mount --bind /dev/shm/tmp /tmp
	evaluate_retval

	boot_mesg "re-mount /var/tmp..."
	mkdir /dev/shm/vartmp
	chmod 1777 /dev/shm/vartmp
	mount --bind /dev/shm/vartmp /var/tmp
	evaluate_retval

	;;
stop)
	umount /var/tmp
	umount /tmp
	boot_mesg "Unmounting all other currently mounted file systems..."
	umount -a -d -r >/dev/null
	evaluate_retval
	;;
*)
	echo "Usage: ${0} {start|stop}"
	exit 1
	;;
esac

# End $rc_base/init.d/mountfs

