#!/bin/bash   
########################################################################
# Begin $rc_base/init.d/setclock
#
# Description : Setting Linux Clock
#
# Authors : Gerard Beekmans - gerard@linuxfromscratch.org
#
# Version : 00.00
#
# Notes :
#
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

CLOCKPARAMS=
case "${UTC}" in
yes|true|1)
	CLOCKPARAMS="${CLOCKPARAMS} --utc"
	INFO="[utc]"
	;;
*)
	CLOCKPARAMS="${CLOCKPARAMS} --localtime"
	INFO="[local]"
	;;
esac
	
case ${1} in
start)
	boot_mesg "Setting system clock $INFO..."
	hwclock --hctosys ${CLOCKPARAMS} >/dev/null
	evaluate_retval
	;;
stop)
	boot_mesg "Setting hardware clock $INFO..."
	hwclock --systohc ${CLOCKPARAMS} >/dev/null
	evaluate_retval
	;;
*)
	echo "Usage: ${0} {start|stop}"
	;;
esac

#end script
